### ISSUE TITLE
Feature request: lazy loading classes within module

### ISSUE THREAD

**Issue by Liam-Deacon** [brettcannon/modutil#9]
Hi @brettcannon - I was wondering if it would be possible to implement some sort of lazy loading of the symbols from within a module/package. Specifically I'm thinking of loading a bunch of classes from different modules into the package `__init__.py` for ease of use for users in a Jupyter notebook, however to do so is currently very expensive for certain classes as they have many dependencies and so it would be great if the user could do something like the following:

```python
# internally in mypkg, MyClass is imported from mypkg.sub
from mypkg import MyClass  # ideally lazy load so symbol is available but module not actually loaded

# load class and module on first use
MyClass()
```

**Comment by brettcannon** [comment]
You could, but it's a more complicated problem as you can't blindly assume a name is a module in this case. You would probably need to list what classes are implemented by what module to know when something should be considered a delayed import for a module versus a specific object from a module.

Thanks for the idea and feel free to reuse code from the package, but I don't plan to add support for this.
